name: keil_disassembly
description: Tool to generated disassembly table from the content of assembly program.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  url_launcher: ^5.7.10

  google_fonts: ^1.1.2
  flutter_icons: ^1.1.0

  flutter_animator: ^2.1.0 # not null safe

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bmc_icon.png

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode.ttf
